server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: yc-picture-backend
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yc_picture
    username: root
    password: 12345678
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true
    # 尽在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delete_flg
      logic-delete-value: 1
      logic-not-delete-value: 0